package ru.yandex.practicum.mymarket.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.r2dbc.core.DatabaseClient;
import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Mono;

@Slf4j
@Configuration
public class DataInitializer {

    @Bean
    public CommandLineRunner initData(DatabaseClient client) {
        return args -> {
            log.info("Initializing database...");

            // Создаем таблицы с кавычками и ВЕРХНИМ РЕГИСТРОМ
            String createItems = """
                CREATE TABLE IF NOT EXISTS "ITEMS" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "TITLE" VARCHAR(255) NOT NULL,
                    "DESCRIPTION" VARCHAR(1000),
                    "IMG_PATH" VARCHAR(255) NOT NULL,
                    "PRICE" BIGINT NOT NULL,
                    "STOCK" INT NOT NULL
                )
                """;

            String createCartItems = """
                CREATE TABLE IF NOT EXISTS "CART_ITEMS" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ITEM_ID" BIGINT NOT NULL,
                    "QUANTITY" INT NOT NULL,
                    "SESSION_ID" VARCHAR(255) NOT NULL
                )
                """;

            String createOrders = """
                CREATE TABLE IF NOT EXISTS "ORDERS" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ORDER_DATE" TIMESTAMP NOT NULL,
                    "TOTAL_SUM" BIGINT NOT NULL
                )
                """;

            String createOrderItems = """
                CREATE TABLE IF NOT EXISTS "ORDER_ITEMS" (
                    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "ORDER_ID" BIGINT NOT NULL,
                    "ITEM_ID" BIGINT NOT NULL,
                    "QUANTITY" INT NOT NULL,
                    "PRICE" BIGINT NOT NULL
                )
                """;

            String insertData = """
                INSERT INTO "ITEMS" ("TITLE", "DESCRIPTION", "IMG_PATH", "PRICE", "STOCK") VALUES
                ('Футбольный мяч', 'Качественный футбольный мяч', 'images/soccer_ball.png', 2500, 20),
                ('Бейсболка красная', 'Красивая красная бейсболка', 'images/baseball_cap_red.png', 1000, 1),
                ('Бейсболка черная', 'Стильная черная бейсболка', 'images/baseball_cap_black.png', 1500, 2),
                ('Зонт', 'супер зонт', 'images/umbrella.png', 1500, 30),
                ('Самолет', 'Реактивный самолет', 'images/airplane.png', 1000000000, 0)
                """;

            // Создаем таблицы последовательно
            client.sql(createItems)
                    .fetch()
                    .rowsUpdated()
                    .doOnSuccess(result -> log.info("Table 'ITEMS' created"))
                    .flatMap(result -> client.sql(createCartItems).fetch().rowsUpdated())
                    .doOnSuccess(result -> log.info("Table 'CART_ITEMS' created"))
                    .flatMap(result -> client.sql(createOrders).fetch().rowsUpdated())
                    .doOnSuccess(result -> log.info("Table 'ORDERS' created"))
                    .flatMap(result -> client.sql(createOrderItems).fetch().rowsUpdated())
                    .doOnSuccess(result -> log.info("Table 'ORDER_ITEMS' created"))
                    .flatMap(result -> client.sql("SELECT COUNT(*) as cnt FROM \"ITEMS\"").fetch().first())
                    .flatMap(result -> {
                        Number count = (Number) result.get("cnt");
                        if (count != null && count.longValue() == 0) {
                            log.info("Inserting test data...");
                            return client.sql(insertData).fetch().rowsUpdated()
                                    .doOnSuccess(rows -> log.info("Inserted {} rows", rows));
                        }
                        log.info("Data already exists, skipping initialization");
                        return Mono.just(0L);
                    })
                    .doOnSuccess(v -> log.info("Database initialization completed!"))
                    .doOnError(e -> log.error("Database initialization failed: {}", e.getMessage()))
                    .block();
        };
    }
}