CREATE TABLE IF NOT EXISTS items (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     title VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    img_path VARCHAR(255) NOT NULL,
    price BIGINT NOT NULL,
    stock INT NOT NULL
    );

CREATE TABLE IF NOT EXISTS cart_items (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          item_id BIGINT NOT NULL,
                                          quantity INT NOT NULL,
                                          session_id VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS orders (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      order_date TIMESTAMP NOT NULL,
                                      total_sum BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS order_items (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           order_id BIGINT NOT NULL,
                                           item_id BIGINT NOT NULL,
                                           quantity INT NOT NULL,
                                           price BIGINT NOT NULL
);