spring.application.name=my-market-app

spring.datasource.url=jdbc:h2:mem:mymarketdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Payment service
payment.service.url=http://localhost:8081

# Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis

# Server
server.port=8080

server.tomcat.uri-encoding=UTF-8
spring.http.encoding.force=true
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true